// Code generated by mockery. DO NOT EDIT.

package repository

import (
	model "github.com/obutora/open-api-mini-layerd-architecture-template/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

type ProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductRepository) EXPECT() *ProductRepository_Expecter {
	return &ProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: product
func (_m *ProductRepository) Create(product *model.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *model.Product
func (_e *ProductRepository_Expecter) Create(product interface{}) *ProductRepository_Create_Call {
	return &ProductRepository_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *ProductRepository_Create_Call) Run(run func(product *model.Product)) *ProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Product))
	})
	return _c
}

func (_c *ProductRepository_Create_Call) Return(_a0 error) *ProductRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepository_Create_Call) RunAndReturn(run func(*model.Product) error) *ProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *ProductRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *ProductRepository_Expecter) Delete(id interface{}) *ProductRepository_Delete_Call {
	return &ProductRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *ProductRepository_Delete_Call) Run(run func(id int)) *ProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ProductRepository_Delete_Call) Return(_a0 error) *ProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepository_Delete_Call) RunAndReturn(run func(int) error) *ProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *ProductRepository) GetByID(id int) (*model.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *ProductRepository_Expecter) GetByID(id interface{}) *ProductRepository_GetByID_Call {
	return &ProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *ProductRepository_GetByID_Call) Run(run func(id int)) *ProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ProductRepository_GetByID_Call) Return(_a0 *model.Product, _a1 error) *ProductRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductRepository_GetByID_Call) RunAndReturn(run func(int) (*model.Product, error)) *ProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: limit, offset
func (_m *ProductRepository) List(limit int, offset int) ([]*model.Product, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*model.Product, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*model.Product); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProductRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *ProductRepository_Expecter) List(limit interface{}, offset interface{}) *ProductRepository_List_Call {
	return &ProductRepository_List_Call{Call: _e.mock.On("List", limit, offset)}
}

func (_c *ProductRepository_List_Call) Run(run func(limit int, offset int)) *ProductRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *ProductRepository_List_Call) Return(_a0 []*model.Product, _a1 error) *ProductRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductRepository_List_Call) RunAndReturn(run func(int, int) ([]*model.Product, error)) *ProductRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: product
func (_m *ProductRepository) Update(product *model.Product) error {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *model.Product
func (_e *ProductRepository_Expecter) Update(product interface{}) *ProductRepository_Update_Call {
	return &ProductRepository_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *ProductRepository_Update_Call) Run(run func(product *model.Product)) *ProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Product))
	})
	return _c
}

func (_c *ProductRepository_Update_Call) Return(_a0 error) *ProductRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductRepository_Update_Call) RunAndReturn(run func(*model.Product) error) *ProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
