basePath: /
definitions:
  dto.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  dto.UpdateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  dto.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.AppError:
    properties:
      code:
        $ref: '#/definitions/model.ErrorCode'
      message:
        type: string
    type: object
  model.ErrorCode:
    enum:
    - NOT_FOUND
    - INVALID_INPUT
    - UNAUTHORIZED
    - BAD_REQUEST
    - INTERNAL_ERROR
    - DUPLICATE
    type: string
    x-enum-varnames:
    - ErrNotFound
    - ErrInvalidInput
    - ErrUnauthorized
    - ErrBadRequest
    - ErrInternalError
    - ErrDuplicate
  model.Payment:
    properties:
      amount:
        type: integer
      id:
        type: integer
      payment_date:
        type: string
    type: object
  model.Questionnaire:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API documentation for the application
  title: API Documentation
  version: "1.0"
paths:
  /api/v1/answer/completion:
    get:
      responses:
        "308":
          description: https://www.google.com/
          schema:
            type: string
      summary: 回答を収集し、Media-Userに通知を送信し、Userをリダイレクトします
  /api/v1/payments:
    get:
      description: 指定された期間の請求情報を取得します
      parameters:
      - description: 開始日
        format: date
        in: query
        name: startDate
        required: true
        type: string
      - description: 終了日
        format: date
        in: query
        name: endDate
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Payment'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
      security:
      - ApiKeyAuth: []
      summary: 指定された期間の請求情報を取得します
      tags:
      - payments
  /api/v1/questionnaires/{id}:
    get:
      description: idの質問票を取得します。ユーザーが一度もplatformを利用していない場合は登録画面にリダイレクトします
      parameters:
      - description: 質問票ID
        in: path
        name: id
        required: true
        type: string
      - description: ユーザーのメールハッシュ
        in: query
        name: hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Questionnaire'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
      summary: 質問票を取得します。
      tags:
      - questionnaires
    patch:
      consumes:
      - application/json
      description: 質問票を更新します
      parameters:
      - description: 質問票ID
        in: path
        name: id
        required: true
        type: string
      - description: 質問票情報
        in: body
        name: questionnaire
        required: true
        schema:
          $ref: '#/definitions/model.Questionnaire'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
      security:
      - ApiKeyAuth: []
      summary: 質問票を更新します
      tags:
      - questionnaires
  /api/v1/questionnaires/{id}/status:
    get:
      description: 質問票のステータスを取得します
      parameters:
      - description: 質問票ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 質問票のステータス
          schema:
            type: int
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
      security:
      - ApiKeyAuth: []
      summary: 質問票のステータスを取得します
      tags:
      - questionnaires
  /api/v1/questionnaires/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Questionnaire'
            type: array
        "401":
          description: 認証エラー
          schema:
            $ref: '#/definitions/model.AppError'
      security:
      - ApiKeyAuth: []
      summary: 質問票のリストを取得します
      tags:
      - questionnaires
  /users:
    get:
      consumes:
      - application/json
      description: ページネーションを使用してユーザー一覧を取得します
      parameters:
      - default: 1
        description: ページ番号
        in: query
        name: page
        type: integer
      - default: 10
        description: 1ページあたりの件数
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.UserResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.AppError'
      summary: ユーザー一覧を取得
      tags:
      - users
    post:
      consumes:
      - application/json
      description: 新しいユーザーを作成します
      parameters:
      - description: ユーザー情報
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.AppError'
      summary: ユーザーを作成
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: 指定されたIDのユーザーを削除します
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.AppError'
      summary: ユーザーを削除
      tags:
      - users
    get:
      consumes:
      - application/json
      description: 指定されたIDのユーザーを取得します
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.AppError'
      summary: ユーザーを取得
      tags:
      - users
    put:
      consumes:
      - application/json
      description: 指定されたIDのユーザー情報を更新します
      parameters:
      - description: ユーザーID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新するユーザー情報
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.AppError'
      summary: ユーザーを更新
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    description: Bearer Tokenによる認証。'Bearer 'プレフィックスの後にJWTトークンを入力してください。
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
